/* 
 * ProcessMaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ProcessMakerSDK.Client;
using ProcessMakerSDK.Model;

namespace ProcessMakerSDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEnvironmentVariablesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Save a new environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>EnvironmentVariables</returns>
        EnvironmentVariables CreateEnvironmentVariables (EnvironmentVariablesEditable environmentVariablesEditable);

        /// <summary>
        /// Save a new environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>ApiResponse of EnvironmentVariables</returns>
        ApiResponse<EnvironmentVariables> CreateEnvironmentVariablesWithHttpInfo (EnvironmentVariablesEditable environmentVariablesEditable);
        /// <summary>
        /// Delete a environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>EnvironmentVariables</returns>
        EnvironmentVariables DeleteEnvironmentVariables (string environmentVariablesId);

        /// <summary>
        /// Delete a environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>ApiResponse of EnvironmentVariables</returns>
        ApiResponse<EnvironmentVariables> DeleteEnvironmentVariablesWithHttpInfo (string environmentVariablesId);
        /// <summary>
        /// Returns all environmentVariables that the user has access to
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>InlineResponse2001</returns>
        InlineResponse2001 GetEnvironmentVariables (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null);

        /// <summary>
        /// Returns all environmentVariables that the user has access to
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>ApiResponse of InlineResponse2001</returns>
        ApiResponse<InlineResponse2001> GetEnvironmentVariablesWithHttpInfo (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null);
        /// <summary>
        /// Get single environment_variables by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>EnvironmentVariables</returns>
        EnvironmentVariables GetEnvironmentVariablesById (string environmentVariablesId);

        /// <summary>
        /// Get single environment_variables by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>ApiResponse of EnvironmentVariables</returns>
        ApiResponse<EnvironmentVariables> GetEnvironmentVariablesByIdWithHttpInfo (string environmentVariablesId);
        /// <summary>
        /// Update a environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>EnvironmentVariables</returns>
        EnvironmentVariables UpdateEnvironmentVariables (string environmentVariablesId, EnvironmentVariablesEditable environmentVariablesEditable);

        /// <summary>
        /// Update a environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>ApiResponse of EnvironmentVariables</returns>
        ApiResponse<EnvironmentVariables> UpdateEnvironmentVariablesWithHttpInfo (string environmentVariablesId, EnvironmentVariablesEditable environmentVariablesEditable);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Save a new environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>Task of EnvironmentVariables</returns>
        System.Threading.Tasks.Task<EnvironmentVariables> CreateEnvironmentVariablesAsync (EnvironmentVariablesEditable environmentVariablesEditable);

        /// <summary>
        /// Save a new environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>Task of ApiResponse (EnvironmentVariables)</returns>
        System.Threading.Tasks.Task<ApiResponse<EnvironmentVariables>> CreateEnvironmentVariablesAsyncWithHttpInfo (EnvironmentVariablesEditable environmentVariablesEditable);
        /// <summary>
        /// Delete a environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>Task of EnvironmentVariables</returns>
        System.Threading.Tasks.Task<EnvironmentVariables> DeleteEnvironmentVariablesAsync (string environmentVariablesId);

        /// <summary>
        /// Delete a environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>Task of ApiResponse (EnvironmentVariables)</returns>
        System.Threading.Tasks.Task<ApiResponse<EnvironmentVariables>> DeleteEnvironmentVariablesAsyncWithHttpInfo (string environmentVariablesId);
        /// <summary>
        /// Returns all environmentVariables that the user has access to
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>Task of InlineResponse2001</returns>
        System.Threading.Tasks.Task<InlineResponse2001> GetEnvironmentVariablesAsync (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null);

        /// <summary>
        /// Returns all environmentVariables that the user has access to
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>Task of ApiResponse (InlineResponse2001)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse2001>> GetEnvironmentVariablesAsyncWithHttpInfo (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null);
        /// <summary>
        /// Get single environment_variables by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>Task of EnvironmentVariables</returns>
        System.Threading.Tasks.Task<EnvironmentVariables> GetEnvironmentVariablesByIdAsync (string environmentVariablesId);

        /// <summary>
        /// Get single environment_variables by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>Task of ApiResponse (EnvironmentVariables)</returns>
        System.Threading.Tasks.Task<ApiResponse<EnvironmentVariables>> GetEnvironmentVariablesByIdAsyncWithHttpInfo (string environmentVariablesId);
        /// <summary>
        /// Update a environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>Task of EnvironmentVariables</returns>
        System.Threading.Tasks.Task<EnvironmentVariables> UpdateEnvironmentVariablesAsync (string environmentVariablesId, EnvironmentVariablesEditable environmentVariablesEditable);

        /// <summary>
        /// Update a environment_variables
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>Task of ApiResponse (EnvironmentVariables)</returns>
        System.Threading.Tasks.Task<ApiResponse<EnvironmentVariables>> UpdateEnvironmentVariablesAsyncWithHttpInfo (string environmentVariablesId, EnvironmentVariablesEditable environmentVariablesEditable);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EnvironmentVariablesApi : IEnvironmentVariablesApi
    {
        private ProcessMakerSDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EnvironmentVariablesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EnvironmentVariablesApi(String basePath)
        {
            this.Configuration = new ProcessMakerSDK.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ProcessMakerSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EnvironmentVariablesApi"/> class
        /// </summary>
        /// <returns></returns>
        public EnvironmentVariablesApi()
        {
            this.Configuration = ProcessMakerSDK.Client.Configuration.Default;

            ExceptionFactory = ProcessMakerSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EnvironmentVariablesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EnvironmentVariablesApi(ProcessMakerSDK.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ProcessMakerSDK.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ProcessMakerSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ProcessMakerSDK.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ProcessMakerSDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Save a new environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>EnvironmentVariables</returns>
        public EnvironmentVariables CreateEnvironmentVariables (EnvironmentVariablesEditable environmentVariablesEditable)
        {
             ApiResponse<EnvironmentVariables> localVarResponse = CreateEnvironmentVariablesWithHttpInfo(environmentVariablesEditable);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Save a new environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>ApiResponse of EnvironmentVariables</returns>
        public ApiResponse< EnvironmentVariables > CreateEnvironmentVariablesWithHttpInfo (EnvironmentVariablesEditable environmentVariablesEditable)
        {
            // verify the required parameter 'environmentVariablesEditable' is set
            if (environmentVariablesEditable == null)
                throw new ApiException(400, "Missing required parameter 'environmentVariablesEditable' when calling EnvironmentVariablesApi->CreateEnvironmentVariables");

            var localVarPath = "/environment_variables";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (environmentVariablesEditable != null && environmentVariablesEditable.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(environmentVariablesEditable); // http body (model) parameter
            }
            else
            {
                localVarPostBody = environmentVariablesEditable; // byte array
            }

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateEnvironmentVariables", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EnvironmentVariables>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (EnvironmentVariables) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvironmentVariables)));
        }

        /// <summary>
        /// Save a new environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>Task of EnvironmentVariables</returns>
        public async System.Threading.Tasks.Task<EnvironmentVariables> CreateEnvironmentVariablesAsync (EnvironmentVariablesEditable environmentVariablesEditable)
        {
             ApiResponse<EnvironmentVariables> localVarResponse = await CreateEnvironmentVariablesAsyncWithHttpInfo(environmentVariablesEditable);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Save a new environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>Task of ApiResponse (EnvironmentVariables)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<EnvironmentVariables>> CreateEnvironmentVariablesAsyncWithHttpInfo (EnvironmentVariablesEditable environmentVariablesEditable)
        {
            // verify the required parameter 'environmentVariablesEditable' is set
            if (environmentVariablesEditable == null)
                throw new ApiException(400, "Missing required parameter 'environmentVariablesEditable' when calling EnvironmentVariablesApi->CreateEnvironmentVariables");

            var localVarPath = "/environment_variables";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (environmentVariablesEditable != null && environmentVariablesEditable.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(environmentVariablesEditable); // http body (model) parameter
            }
            else
            {
                localVarPostBody = environmentVariablesEditable; // byte array
            }

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateEnvironmentVariables", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EnvironmentVariables>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (EnvironmentVariables) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvironmentVariables)));
        }

        /// <summary>
        /// Delete a environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>EnvironmentVariables</returns>
        public EnvironmentVariables DeleteEnvironmentVariables (string environmentVariablesId)
        {
             ApiResponse<EnvironmentVariables> localVarResponse = DeleteEnvironmentVariablesWithHttpInfo(environmentVariablesId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>ApiResponse of EnvironmentVariables</returns>
        public ApiResponse< EnvironmentVariables > DeleteEnvironmentVariablesWithHttpInfo (string environmentVariablesId)
        {
            // verify the required parameter 'environmentVariablesId' is set
            if (environmentVariablesId == null)
                throw new ApiException(400, "Missing required parameter 'environmentVariablesId' when calling EnvironmentVariablesApi->DeleteEnvironmentVariables");

            var localVarPath = "/environment_variables/{environment_variables_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (environmentVariablesId != null) localVarPathParams.Add("environment_variables_id", this.Configuration.ApiClient.ParameterToString(environmentVariablesId)); // path parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteEnvironmentVariables", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EnvironmentVariables>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (EnvironmentVariables) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvironmentVariables)));
        }

        /// <summary>
        /// Delete a environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>Task of EnvironmentVariables</returns>
        public async System.Threading.Tasks.Task<EnvironmentVariables> DeleteEnvironmentVariablesAsync (string environmentVariablesId)
        {
             ApiResponse<EnvironmentVariables> localVarResponse = await DeleteEnvironmentVariablesAsyncWithHttpInfo(environmentVariablesId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete a environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>Task of ApiResponse (EnvironmentVariables)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<EnvironmentVariables>> DeleteEnvironmentVariablesAsyncWithHttpInfo (string environmentVariablesId)
        {
            // verify the required parameter 'environmentVariablesId' is set
            if (environmentVariablesId == null)
                throw new ApiException(400, "Missing required parameter 'environmentVariablesId' when calling EnvironmentVariablesApi->DeleteEnvironmentVariables");

            var localVarPath = "/environment_variables/{environment_variables_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (environmentVariablesId != null) localVarPathParams.Add("environment_variables_id", this.Configuration.ApiClient.ParameterToString(environmentVariablesId)); // path parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteEnvironmentVariables", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EnvironmentVariables>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (EnvironmentVariables) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvironmentVariables)));
        }

        /// <summary>
        /// Returns all environmentVariables that the user has access to 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>InlineResponse2001</returns>
        public InlineResponse2001 GetEnvironmentVariables (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null)
        {
             ApiResponse<InlineResponse2001> localVarResponse = GetEnvironmentVariablesWithHttpInfo(filter, orderBy, orderDirection, perPage, include);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns all environmentVariables that the user has access to 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>ApiResponse of InlineResponse2001</returns>
        public ApiResponse< InlineResponse2001 > GetEnvironmentVariablesWithHttpInfo (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null)
        {

            var localVarPath = "/environment_variables";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (filter != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter", filter)); // query parameter
            if (orderBy != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "order_by", orderBy)); // query parameter
            if (orderDirection != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "order_direction", orderDirection)); // query parameter
            if (perPage != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "per_page", perPage)); // query parameter
            if (include != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include", include)); // query parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEnvironmentVariables", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2001>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (InlineResponse2001) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2001)));
        }

        /// <summary>
        /// Returns all environmentVariables that the user has access to 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>Task of InlineResponse2001</returns>
        public async System.Threading.Tasks.Task<InlineResponse2001> GetEnvironmentVariablesAsync (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null)
        {
             ApiResponse<InlineResponse2001> localVarResponse = await GetEnvironmentVariablesAsyncWithHttpInfo(filter, orderBy, orderDirection, perPage, include);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns all environmentVariables that the user has access to 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>Task of ApiResponse (InlineResponse2001)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InlineResponse2001>> GetEnvironmentVariablesAsyncWithHttpInfo (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null)
        {

            var localVarPath = "/environment_variables";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (filter != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter", filter)); // query parameter
            if (orderBy != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "order_by", orderBy)); // query parameter
            if (orderDirection != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "order_direction", orderDirection)); // query parameter
            if (perPage != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "per_page", perPage)); // query parameter
            if (include != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include", include)); // query parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEnvironmentVariables", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2001>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (InlineResponse2001) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2001)));
        }

        /// <summary>
        /// Get single environment_variables by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>EnvironmentVariables</returns>
        public EnvironmentVariables GetEnvironmentVariablesById (string environmentVariablesId)
        {
             ApiResponse<EnvironmentVariables> localVarResponse = GetEnvironmentVariablesByIdWithHttpInfo(environmentVariablesId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get single environment_variables by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>ApiResponse of EnvironmentVariables</returns>
        public ApiResponse< EnvironmentVariables > GetEnvironmentVariablesByIdWithHttpInfo (string environmentVariablesId)
        {
            // verify the required parameter 'environmentVariablesId' is set
            if (environmentVariablesId == null)
                throw new ApiException(400, "Missing required parameter 'environmentVariablesId' when calling EnvironmentVariablesApi->GetEnvironmentVariablesById");

            var localVarPath = "/environment_variables/{environment_variables_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (environmentVariablesId != null) localVarPathParams.Add("environment_variables_id", this.Configuration.ApiClient.ParameterToString(environmentVariablesId)); // path parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEnvironmentVariablesById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EnvironmentVariables>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (EnvironmentVariables) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvironmentVariables)));
        }

        /// <summary>
        /// Get single environment_variables by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>Task of EnvironmentVariables</returns>
        public async System.Threading.Tasks.Task<EnvironmentVariables> GetEnvironmentVariablesByIdAsync (string environmentVariablesId)
        {
             ApiResponse<EnvironmentVariables> localVarResponse = await GetEnvironmentVariablesByIdAsyncWithHttpInfo(environmentVariablesId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get single environment_variables by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <returns>Task of ApiResponse (EnvironmentVariables)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<EnvironmentVariables>> GetEnvironmentVariablesByIdAsyncWithHttpInfo (string environmentVariablesId)
        {
            // verify the required parameter 'environmentVariablesId' is set
            if (environmentVariablesId == null)
                throw new ApiException(400, "Missing required parameter 'environmentVariablesId' when calling EnvironmentVariablesApi->GetEnvironmentVariablesById");

            var localVarPath = "/environment_variables/{environment_variables_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (environmentVariablesId != null) localVarPathParams.Add("environment_variables_id", this.Configuration.ApiClient.ParameterToString(environmentVariablesId)); // path parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEnvironmentVariablesById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EnvironmentVariables>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (EnvironmentVariables) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvironmentVariables)));
        }

        /// <summary>
        /// Update a environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>EnvironmentVariables</returns>
        public EnvironmentVariables UpdateEnvironmentVariables (string environmentVariablesId, EnvironmentVariablesEditable environmentVariablesEditable)
        {
             ApiResponse<EnvironmentVariables> localVarResponse = UpdateEnvironmentVariablesWithHttpInfo(environmentVariablesId, environmentVariablesEditable);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update a environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>ApiResponse of EnvironmentVariables</returns>
        public ApiResponse< EnvironmentVariables > UpdateEnvironmentVariablesWithHttpInfo (string environmentVariablesId, EnvironmentVariablesEditable environmentVariablesEditable)
        {
            // verify the required parameter 'environmentVariablesId' is set
            if (environmentVariablesId == null)
                throw new ApiException(400, "Missing required parameter 'environmentVariablesId' when calling EnvironmentVariablesApi->UpdateEnvironmentVariables");
            // verify the required parameter 'environmentVariablesEditable' is set
            if (environmentVariablesEditable == null)
                throw new ApiException(400, "Missing required parameter 'environmentVariablesEditable' when calling EnvironmentVariablesApi->UpdateEnvironmentVariables");

            var localVarPath = "/environment_variables/{environment_variables_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (environmentVariablesId != null) localVarPathParams.Add("environment_variables_id", this.Configuration.ApiClient.ParameterToString(environmentVariablesId)); // path parameter
            if (environmentVariablesEditable != null && environmentVariablesEditable.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(environmentVariablesEditable); // http body (model) parameter
            }
            else
            {
                localVarPostBody = environmentVariablesEditable; // byte array
            }

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateEnvironmentVariables", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EnvironmentVariables>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (EnvironmentVariables) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvironmentVariables)));
        }

        /// <summary>
        /// Update a environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>Task of EnvironmentVariables</returns>
        public async System.Threading.Tasks.Task<EnvironmentVariables> UpdateEnvironmentVariablesAsync (string environmentVariablesId, EnvironmentVariablesEditable environmentVariablesEditable)
        {
             ApiResponse<EnvironmentVariables> localVarResponse = await UpdateEnvironmentVariablesAsyncWithHttpInfo(environmentVariablesId, environmentVariablesEditable);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update a environment_variables 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentVariablesId">ID of environment_variables to return</param>
        /// <param name="environmentVariablesEditable"></param>
        /// <returns>Task of ApiResponse (EnvironmentVariables)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<EnvironmentVariables>> UpdateEnvironmentVariablesAsyncWithHttpInfo (string environmentVariablesId, EnvironmentVariablesEditable environmentVariablesEditable)
        {
            // verify the required parameter 'environmentVariablesId' is set
            if (environmentVariablesId == null)
                throw new ApiException(400, "Missing required parameter 'environmentVariablesId' when calling EnvironmentVariablesApi->UpdateEnvironmentVariables");
            // verify the required parameter 'environmentVariablesEditable' is set
            if (environmentVariablesEditable == null)
                throw new ApiException(400, "Missing required parameter 'environmentVariablesEditable' when calling EnvironmentVariablesApi->UpdateEnvironmentVariables");

            var localVarPath = "/environment_variables/{environment_variables_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (environmentVariablesId != null) localVarPathParams.Add("environment_variables_id", this.Configuration.ApiClient.ParameterToString(environmentVariablesId)); // path parameter
            if (environmentVariablesEditable != null && environmentVariablesEditable.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(environmentVariablesEditable); // http body (model) parameter
            }
            else
            {
                localVarPostBody = environmentVariablesEditable; // byte array
            }

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateEnvironmentVariables", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EnvironmentVariables>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (EnvironmentVariables) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvironmentVariables)));
        }

    }
}
