/* 
 * ProcessMaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ProcessMakerSDK.Client;
using ProcessMakerSDK.Model;

namespace ProcessMakerSDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IScreensApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Save a new screens
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensEditable"></param>
        /// <returns>Screens</returns>
        Screens CreateScreens (ScreensEditable screensEditable);

        /// <summary>
        /// Save a new screens
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensEditable"></param>
        /// <returns>ApiResponse of Screens</returns>
        ApiResponse<Screens> CreateScreensWithHttpInfo (ScreensEditable screensEditable);
        /// <summary>
        /// Delete a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Screens</returns>
        Screens DeleteScreen (string screensId);

        /// <summary>
        /// Delete a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>ApiResponse of Screens</returns>
        ApiResponse<Screens> DeleteScreenWithHttpInfo (string screensId);
        /// <summary>
        /// duplicate a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Screens</returns>
        Screens DuplicateScript (string screensId, ScreensEditable screensEditable);

        /// <summary>
        /// duplicate a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>ApiResponse of Screens</returns>
        ApiResponse<Screens> DuplicateScriptWithHttpInfo (string screensId, ScreensEditable screensEditable);
        /// <summary>
        /// Export a single screen by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Screens</returns>
        Screens ExportScreen (string screensId);

        /// <summary>
        /// Export a single screen by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>ApiResponse of Screens</returns>
        ApiResponse<Screens> ExportScreenWithHttpInfo (string screensId);
        /// <summary>
        /// Returns all screens that the user has access to
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>InlineResponse20016</returns>
        InlineResponse20016 GetScreens (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null);

        /// <summary>
        /// Returns all screens that the user has access to
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>ApiResponse of InlineResponse20016</returns>
        ApiResponse<InlineResponse20016> GetScreensWithHttpInfo (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null);
        /// <summary>
        /// Get single screens by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screens to return</param>
        /// <returns>Screens</returns>
        Screens GetScreensById (string screensId);

        /// <summary>
        /// Get single screens by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screens to return</param>
        /// <returns>ApiResponse of Screens</returns>
        ApiResponse<Screens> GetScreensByIdWithHttpInfo (string screensId);
        /// <summary>
        /// Import a new screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">file to upload</param>
        /// <returns>Screens</returns>
        Screens ImportScreen (System.IO.Stream file);

        /// <summary>
        /// Import a new screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">file to upload</param>
        /// <returns>ApiResponse of Screens</returns>
        ApiResponse<Screens> ImportScreenWithHttpInfo (System.IO.Stream file);
        /// <summary>
        /// Update a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Screens</returns>
        Screens UpdateScreen (string screensId, ScreensEditable screensEditable);

        /// <summary>
        /// Update a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>ApiResponse of Screens</returns>
        ApiResponse<Screens> UpdateScreenWithHttpInfo (string screensId, ScreensEditable screensEditable);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Save a new screens
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensEditable"></param>
        /// <returns>Task of Screens</returns>
        System.Threading.Tasks.Task<Screens> CreateScreensAsync (ScreensEditable screensEditable);

        /// <summary>
        /// Save a new screens
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensEditable"></param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        System.Threading.Tasks.Task<ApiResponse<Screens>> CreateScreensAsyncWithHttpInfo (ScreensEditable screensEditable);
        /// <summary>
        /// Delete a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Task of Screens</returns>
        System.Threading.Tasks.Task<Screens> DeleteScreenAsync (string screensId);

        /// <summary>
        /// Delete a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        System.Threading.Tasks.Task<ApiResponse<Screens>> DeleteScreenAsyncWithHttpInfo (string screensId);
        /// <summary>
        /// duplicate a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Task of Screens</returns>
        System.Threading.Tasks.Task<Screens> DuplicateScriptAsync (string screensId, ScreensEditable screensEditable);

        /// <summary>
        /// duplicate a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        System.Threading.Tasks.Task<ApiResponse<Screens>> DuplicateScriptAsyncWithHttpInfo (string screensId, ScreensEditable screensEditable);
        /// <summary>
        /// Export a single screen by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Task of Screens</returns>
        System.Threading.Tasks.Task<Screens> ExportScreenAsync (string screensId);

        /// <summary>
        /// Export a single screen by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        System.Threading.Tasks.Task<ApiResponse<Screens>> ExportScreenAsyncWithHttpInfo (string screensId);
        /// <summary>
        /// Returns all screens that the user has access to
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>Task of InlineResponse20016</returns>
        System.Threading.Tasks.Task<InlineResponse20016> GetScreensAsync (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null);

        /// <summary>
        /// Returns all screens that the user has access to
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>Task of ApiResponse (InlineResponse20016)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse20016>> GetScreensAsyncWithHttpInfo (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null);
        /// <summary>
        /// Get single screens by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screens to return</param>
        /// <returns>Task of Screens</returns>
        System.Threading.Tasks.Task<Screens> GetScreensByIdAsync (string screensId);

        /// <summary>
        /// Get single screens by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screens to return</param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        System.Threading.Tasks.Task<ApiResponse<Screens>> GetScreensByIdAsyncWithHttpInfo (string screensId);
        /// <summary>
        /// Import a new screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">file to upload</param>
        /// <returns>Task of Screens</returns>
        System.Threading.Tasks.Task<Screens> ImportScreenAsync (System.IO.Stream file);

        /// <summary>
        /// Import a new screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">file to upload</param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        System.Threading.Tasks.Task<ApiResponse<Screens>> ImportScreenAsyncWithHttpInfo (System.IO.Stream file);
        /// <summary>
        /// Update a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Task of Screens</returns>
        System.Threading.Tasks.Task<Screens> UpdateScreenAsync (string screensId, ScreensEditable screensEditable);

        /// <summary>
        /// Update a screen
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        System.Threading.Tasks.Task<ApiResponse<Screens>> UpdateScreenAsyncWithHttpInfo (string screensId, ScreensEditable screensEditable);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ScreensApi : IScreensApi
    {
        private ProcessMakerSDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ScreensApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ScreensApi(String basePath)
        {
            this.Configuration = new ProcessMakerSDK.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ProcessMakerSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScreensApi"/> class
        /// </summary>
        /// <returns></returns>
        public ScreensApi()
        {
            this.Configuration = ProcessMakerSDK.Client.Configuration.Default;

            ExceptionFactory = ProcessMakerSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScreensApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ScreensApi(ProcessMakerSDK.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ProcessMakerSDK.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ProcessMakerSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ProcessMakerSDK.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ProcessMakerSDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Save a new screens 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensEditable"></param>
        /// <returns>Screens</returns>
        public Screens CreateScreens (ScreensEditable screensEditable)
        {
             ApiResponse<Screens> localVarResponse = CreateScreensWithHttpInfo(screensEditable);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Save a new screens 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensEditable"></param>
        /// <returns>ApiResponse of Screens</returns>
        public ApiResponse< Screens > CreateScreensWithHttpInfo (ScreensEditable screensEditable)
        {
            // verify the required parameter 'screensEditable' is set
            if (screensEditable == null)
                throw new ApiException(400, "Missing required parameter 'screensEditable' when calling ScreensApi->CreateScreens");

            var localVarPath = "/screens";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensEditable != null && screensEditable.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(screensEditable); // http body (model) parameter
            }
            else
            {
                localVarPostBody = screensEditable; // byte array
            }

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateScreens", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Save a new screens 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensEditable"></param>
        /// <returns>Task of Screens</returns>
        public async System.Threading.Tasks.Task<Screens> CreateScreensAsync (ScreensEditable screensEditable)
        {
             ApiResponse<Screens> localVarResponse = await CreateScreensAsyncWithHttpInfo(screensEditable);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Save a new screens 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensEditable"></param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Screens>> CreateScreensAsyncWithHttpInfo (ScreensEditable screensEditable)
        {
            // verify the required parameter 'screensEditable' is set
            if (screensEditable == null)
                throw new ApiException(400, "Missing required parameter 'screensEditable' when calling ScreensApi->CreateScreens");

            var localVarPath = "/screens";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensEditable != null && screensEditable.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(screensEditable); // http body (model) parameter
            }
            else
            {
                localVarPostBody = screensEditable; // byte array
            }

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateScreens", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Delete a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Screens</returns>
        public Screens DeleteScreen (string screensId)
        {
             ApiResponse<Screens> localVarResponse = DeleteScreenWithHttpInfo(screensId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>ApiResponse of Screens</returns>
        public ApiResponse< Screens > DeleteScreenWithHttpInfo (string screensId)
        {
            // verify the required parameter 'screensId' is set
            if (screensId == null)
                throw new ApiException(400, "Missing required parameter 'screensId' when calling ScreensApi->DeleteScreen");

            var localVarPath = "/screens/screensId";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensId != null) localVarPathParams.Add("screens_id", this.Configuration.ApiClient.ParameterToString(screensId)); // path parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteScreen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Delete a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Task of Screens</returns>
        public async System.Threading.Tasks.Task<Screens> DeleteScreenAsync (string screensId)
        {
             ApiResponse<Screens> localVarResponse = await DeleteScreenAsyncWithHttpInfo(screensId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Screens>> DeleteScreenAsyncWithHttpInfo (string screensId)
        {
            // verify the required parameter 'screensId' is set
            if (screensId == null)
                throw new ApiException(400, "Missing required parameter 'screensId' when calling ScreensApi->DeleteScreen");

            var localVarPath = "/screens/screensId";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensId != null) localVarPathParams.Add("screens_id", this.Configuration.ApiClient.ParameterToString(screensId)); // path parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteScreen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// duplicate a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Screens</returns>
        public Screens DuplicateScript (string screensId, ScreensEditable screensEditable)
        {
             ApiResponse<Screens> localVarResponse = DuplicateScriptWithHttpInfo(screensId, screensEditable);
             return localVarResponse.Data;
        }

        /// <summary>
        /// duplicate a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>ApiResponse of Screens</returns>
        public ApiResponse< Screens > DuplicateScriptWithHttpInfo (string screensId, ScreensEditable screensEditable)
        {
            // verify the required parameter 'screensId' is set
            if (screensId == null)
                throw new ApiException(400, "Missing required parameter 'screensId' when calling ScreensApi->DuplicateScript");
            // verify the required parameter 'screensEditable' is set
            if (screensEditable == null)
                throw new ApiException(400, "Missing required parameter 'screensEditable' when calling ScreensApi->DuplicateScript");

            var localVarPath = "/screens/screensId/duplicate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensId != null) localVarPathParams.Add("screens_id", this.Configuration.ApiClient.ParameterToString(screensId)); // path parameter
            if (screensEditable != null && screensEditable.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(screensEditable); // http body (model) parameter
            }
            else
            {
                localVarPostBody = screensEditable; // byte array
            }

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DuplicateScript", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// duplicate a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Task of Screens</returns>
        public async System.Threading.Tasks.Task<Screens> DuplicateScriptAsync (string screensId, ScreensEditable screensEditable)
        {
             ApiResponse<Screens> localVarResponse = await DuplicateScriptAsyncWithHttpInfo(screensId, screensEditable);
             return localVarResponse.Data;

        }

        /// <summary>
        /// duplicate a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Screens>> DuplicateScriptAsyncWithHttpInfo (string screensId, ScreensEditable screensEditable)
        {
            // verify the required parameter 'screensId' is set
            if (screensId == null)
                throw new ApiException(400, "Missing required parameter 'screensId' when calling ScreensApi->DuplicateScript");
            // verify the required parameter 'screensEditable' is set
            if (screensEditable == null)
                throw new ApiException(400, "Missing required parameter 'screensEditable' when calling ScreensApi->DuplicateScript");

            var localVarPath = "/screens/screensId/duplicate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensId != null) localVarPathParams.Add("screens_id", this.Configuration.ApiClient.ParameterToString(screensId)); // path parameter
            if (screensEditable != null && screensEditable.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(screensEditable); // http body (model) parameter
            }
            else
            {
                localVarPostBody = screensEditable; // byte array
            }

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DuplicateScript", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Export a single screen by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Screens</returns>
        public Screens ExportScreen (string screensId)
        {
             ApiResponse<Screens> localVarResponse = ExportScreenWithHttpInfo(screensId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Export a single screen by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>ApiResponse of Screens</returns>
        public ApiResponse< Screens > ExportScreenWithHttpInfo (string screensId)
        {
            // verify the required parameter 'screensId' is set
            if (screensId == null)
                throw new ApiException(400, "Missing required parameter 'screensId' when calling ScreensApi->ExportScreen");

            var localVarPath = "/screens/screensId/export";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensId != null) localVarPathParams.Add("screensId", this.Configuration.ApiClient.ParameterToString(screensId)); // path parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExportScreen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Export a single screen by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Task of Screens</returns>
        public async System.Threading.Tasks.Task<Screens> ExportScreenAsync (string screensId)
        {
             ApiResponse<Screens> localVarResponse = await ExportScreenAsyncWithHttpInfo(screensId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Export a single screen by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Screens>> ExportScreenAsyncWithHttpInfo (string screensId)
        {
            // verify the required parameter 'screensId' is set
            if (screensId == null)
                throw new ApiException(400, "Missing required parameter 'screensId' when calling ScreensApi->ExportScreen");

            var localVarPath = "/screens/screensId/export";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensId != null) localVarPathParams.Add("screensId", this.Configuration.ApiClient.ParameterToString(screensId)); // path parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExportScreen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Returns all screens that the user has access to 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>InlineResponse20016</returns>
        public InlineResponse20016 GetScreens (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null)
        {
             ApiResponse<InlineResponse20016> localVarResponse = GetScreensWithHttpInfo(filter, orderBy, orderDirection, perPage, include);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns all screens that the user has access to 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>ApiResponse of InlineResponse20016</returns>
        public ApiResponse< InlineResponse20016 > GetScreensWithHttpInfo (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null)
        {

            var localVarPath = "/screens";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (filter != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter", filter)); // query parameter
            if (orderBy != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "order_by", orderBy)); // query parameter
            if (orderDirection != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "order_direction", orderDirection)); // query parameter
            if (perPage != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "per_page", perPage)); // query parameter
            if (include != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include", include)); // query parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetScreens", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse20016>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (InlineResponse20016) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse20016)));
        }

        /// <summary>
        /// Returns all screens that the user has access to 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>Task of InlineResponse20016</returns>
        public async System.Threading.Tasks.Task<InlineResponse20016> GetScreensAsync (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null)
        {
             ApiResponse<InlineResponse20016> localVarResponse = await GetScreensAsyncWithHttpInfo(filter, orderBy, orderDirection, perPage, include);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns all screens that the user has access to 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring. (optional)</param>
        /// <param name="orderBy">Field to order results by (optional)</param>
        /// <param name="orderDirection"> (optional, default to asc)</param>
        /// <param name="perPage"> (optional)</param>
        /// <param name="include">Include data from related models in payload. Comma seperated list. (optional, default to &quot;&quot;)</param>
        /// <returns>Task of ApiResponse (InlineResponse20016)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InlineResponse20016>> GetScreensAsyncWithHttpInfo (string filter = null, string orderBy = null, string orderDirection = null, int? perPage = null, string include = null)
        {

            var localVarPath = "/screens";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (filter != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter", filter)); // query parameter
            if (orderBy != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "order_by", orderBy)); // query parameter
            if (orderDirection != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "order_direction", orderDirection)); // query parameter
            if (perPage != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "per_page", perPage)); // query parameter
            if (include != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "include", include)); // query parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetScreens", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse20016>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (InlineResponse20016) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse20016)));
        }

        /// <summary>
        /// Get single screens by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screens to return</param>
        /// <returns>Screens</returns>
        public Screens GetScreensById (string screensId)
        {
             ApiResponse<Screens> localVarResponse = GetScreensByIdWithHttpInfo(screensId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get single screens by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screens to return</param>
        /// <returns>ApiResponse of Screens</returns>
        public ApiResponse< Screens > GetScreensByIdWithHttpInfo (string screensId)
        {
            // verify the required parameter 'screensId' is set
            if (screensId == null)
                throw new ApiException(400, "Missing required parameter 'screensId' when calling ScreensApi->GetScreensById");

            var localVarPath = "/screens/screensId";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensId != null) localVarPathParams.Add("screens_id", this.Configuration.ApiClient.ParameterToString(screensId)); // path parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetScreensById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Get single screens by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screens to return</param>
        /// <returns>Task of Screens</returns>
        public async System.Threading.Tasks.Task<Screens> GetScreensByIdAsync (string screensId)
        {
             ApiResponse<Screens> localVarResponse = await GetScreensByIdAsyncWithHttpInfo(screensId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get single screens by ID 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screens to return</param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Screens>> GetScreensByIdAsyncWithHttpInfo (string screensId)
        {
            // verify the required parameter 'screensId' is set
            if (screensId == null)
                throw new ApiException(400, "Missing required parameter 'screensId' when calling ScreensApi->GetScreensById");

            var localVarPath = "/screens/screensId";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensId != null) localVarPathParams.Add("screens_id", this.Configuration.ApiClient.ParameterToString(screensId)); // path parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetScreensById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Import a new screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">file to upload</param>
        /// <returns>Screens</returns>
        public Screens ImportScreen (System.IO.Stream file)
        {
             ApiResponse<Screens> localVarResponse = ImportScreenWithHttpInfo(file);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Import a new screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">file to upload</param>
        /// <returns>ApiResponse of Screens</returns>
        public ApiResponse< Screens > ImportScreenWithHttpInfo (System.IO.Stream file)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new ApiException(400, "Missing required parameter 'file' when calling ScreensApi->ImportScreen");

            var localVarPath = "/screens/import";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (file != null) localVarFormParams.Add("file", this.Configuration.ApiClient.ParameterToString(file)); // form parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ImportScreen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Import a new screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">file to upload</param>
        /// <returns>Task of Screens</returns>
        public async System.Threading.Tasks.Task<Screens> ImportScreenAsync (System.IO.Stream file)
        {
             ApiResponse<Screens> localVarResponse = await ImportScreenAsyncWithHttpInfo(file);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Import a new screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">file to upload</param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Screens>> ImportScreenAsyncWithHttpInfo (System.IO.Stream file)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new ApiException(400, "Missing required parameter 'file' when calling ScreensApi->ImportScreen");

            var localVarPath = "/screens/import";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (file != null) localVarFormParams.Add("file", this.Configuration.ApiClient.ParameterToString(file)); // form parameter

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ImportScreen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Update a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Screens</returns>
        public Screens UpdateScreen (string screensId, ScreensEditable screensEditable)
        {
             ApiResponse<Screens> localVarResponse = UpdateScreenWithHttpInfo(screensId, screensEditable);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>ApiResponse of Screens</returns>
        public ApiResponse< Screens > UpdateScreenWithHttpInfo (string screensId, ScreensEditable screensEditable)
        {
            // verify the required parameter 'screensId' is set
            if (screensId == null)
                throw new ApiException(400, "Missing required parameter 'screensId' when calling ScreensApi->UpdateScreen");
            // verify the required parameter 'screensEditable' is set
            if (screensEditable == null)
                throw new ApiException(400, "Missing required parameter 'screensEditable' when calling ScreensApi->UpdateScreen");

            var localVarPath = "/screens/screensId";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensId != null) localVarPathParams.Add("screens_id", this.Configuration.ApiClient.ParameterToString(screensId)); // path parameter
            if (screensEditable != null && screensEditable.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(screensEditable); // http body (model) parameter
            }
            else
            {
                localVarPostBody = screensEditable; // byte array
            }

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateScreen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

        /// <summary>
        /// Update a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Task of Screens</returns>
        public async System.Threading.Tasks.Task<Screens> UpdateScreenAsync (string screensId, ScreensEditable screensEditable)
        {
             ApiResponse<Screens> localVarResponse = await UpdateScreenAsyncWithHttpInfo(screensId, screensEditable);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update a screen 
        /// </summary>
        /// <exception cref="ProcessMakerSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="screensId">ID of screen to return</param>
        /// <param name="screensEditable"></param>
        /// <returns>Task of ApiResponse (Screens)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Screens>> UpdateScreenAsyncWithHttpInfo (string screensId, ScreensEditable screensEditable)
        {
            // verify the required parameter 'screensId' is set
            if (screensId == null)
                throw new ApiException(400, "Missing required parameter 'screensId' when calling ScreensApi->UpdateScreen");
            // verify the required parameter 'screensEditable' is set
            if (screensEditable == null)
                throw new ApiException(400, "Missing required parameter 'screensEditable' when calling ScreensApi->UpdateScreen");

            var localVarPath = "/screens/screensId";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (screensId != null) localVarPathParams.Add("screens_id", this.Configuration.ApiClient.ParameterToString(screensId)); // path parameter
            if (screensEditable != null && screensEditable.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(screensEditable); // http body (model) parameter
            }
            else
            {
                localVarPostBody = screensEditable; // byte array
            }

            // authentication (pm_api_auth_code) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }
            // authentication (pm_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateScreen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Screens>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Screens) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Screens)));
        }

    }
}
