/* 
 * ProcessMaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProcessMakerSDK.Api;
using ProcessMakerSDK.Model;
using ProcessMakerSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProcessMakerSDK.Test
{
    /// <summary>
    ///  Class for testing EnvironmentVariablesEditable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnvironmentVariablesEditableTests
    {
        // TODO uncomment below to declare an instance variable for EnvironmentVariablesEditable
        //private EnvironmentVariablesEditable instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnvironmentVariablesEditable
            //instance = new EnvironmentVariablesEditable();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvironmentVariablesEditable
        /// </summary>
        [Test]
        public void EnvironmentVariablesEditableInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EnvironmentVariablesEditable
            //Assert.IsInstanceOf(typeof(EnvironmentVariablesEditable), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
