/* 
 * ProcessMaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProcessMakerSDK.Api;
using ProcessMakerSDK.Model;
using ProcessMakerSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProcessMakerSDK.Test
{
    /// <summary>
    ///  Class for testing GroupsAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupsAllOfTests
    {
        // TODO uncomment below to declare an instance variable for GroupsAllOf
        //private GroupsAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupsAllOf
            //instance = new GroupsAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupsAllOf
        /// </summary>
        [Test]
        public void GroupsAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GroupsAllOf
            //Assert.IsInstanceOf(typeof(GroupsAllOf), instance);
        }


        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
