/* 
 * ProcessMaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProcessMakerSDK.Api;
using ProcessMakerSDK.Model;
using ProcessMakerSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProcessMakerSDK.Test
{
    /// <summary>
    ///  Class for testing InlineObject6
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject6Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject6
        //private InlineObject6 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject6
            //instance = new InlineObject6();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject6
        /// </summary>
        [Test]
        public void InlineObject6InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject6
            //Assert.IsInstanceOf(typeof(InlineObject6), instance);
        }


        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }

    }

}
