/* 
 * ProcessMaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProcessMakerSDK.Api;
using ProcessMakerSDK.Model;
using ProcessMakerSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProcessMakerSDK.Test
{
    /// <summary>
    ///  Class for testing MediaEditable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MediaEditableTests
    {
        // TODO uncomment below to declare an instance variable for MediaEditable
        //private MediaEditable instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaEditable
            //instance = new MediaEditable();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaEditable
        /// </summary>
        [Test]
        public void MediaEditableInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MediaEditable
            //Assert.IsInstanceOf(typeof(MediaEditable), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ModelId'
        /// </summary>
        [Test]
        public void ModelIdTest()
        {
            // TODO unit test for the property 'ModelId'
        }
        /// <summary>
        /// Test the property 'ModelType'
        /// </summary>
        [Test]
        public void ModelTypeTest()
        {
            // TODO unit test for the property 'ModelType'
        }
        /// <summary>
        /// Test the property 'CollectionName'
        /// </summary>
        [Test]
        public void CollectionNameTest()
        {
            // TODO unit test for the property 'CollectionName'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Test]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
        /// <summary>
        /// Test the property 'Disk'
        /// </summary>
        [Test]
        public void DiskTest()
        {
            // TODO unit test for the property 'Disk'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Manipulations'
        /// </summary>
        [Test]
        public void ManipulationsTest()
        {
            // TODO unit test for the property 'Manipulations'
        }
        /// <summary>
        /// Test the property 'CustomProperties'
        /// </summary>
        [Test]
        public void CustomPropertiesTest()
        {
            // TODO unit test for the property 'CustomProperties'
        }
        /// <summary>
        /// Test the property 'ResponsiveImages'
        /// </summary>
        [Test]
        public void ResponsiveImagesTest()
        {
            // TODO unit test for the property 'ResponsiveImages'
        }
        /// <summary>
        /// Test the property 'OrderColumn'
        /// </summary>
        [Test]
        public void OrderColumnTest()
        {
            // TODO unit test for the property 'OrderColumn'
        }

    }

}
