/* 
 * ProcessMaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProcessMakerSDK.Api;
using ProcessMakerSDK.Model;
using ProcessMakerSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ProcessMakerSDK.Test
{
    /// <summary>
    ///  Class for testing ProcessPermissions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessPermissionsTests
    {
        // TODO uncomment below to declare an instance variable for ProcessPermissions
        //private ProcessPermissions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessPermissions
            //instance = new ProcessPermissions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessPermissions
        /// </summary>
        [Test]
        public void ProcessPermissionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ProcessPermissions
            //Assert.IsInstanceOf(typeof(ProcessPermissions), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ProcessId'
        /// </summary>
        [Test]
        public void ProcessIdTest()
        {
            // TODO unit test for the property 'ProcessId'
        }
        /// <summary>
        /// Test the property 'PermissionId'
        /// </summary>
        [Test]
        public void PermissionIdTest()
        {
            // TODO unit test for the property 'PermissionId'
        }
        /// <summary>
        /// Test the property 'AssignableId'
        /// </summary>
        [Test]
        public void AssignableIdTest()
        {
            // TODO unit test for the property 'AssignableId'
        }
        /// <summary>
        /// Test the property 'AssignableType'
        /// </summary>
        [Test]
        public void AssignableTypeTest()
        {
            // TODO unit test for the property 'AssignableType'
        }

    }

}
